name: Build

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    uses: CrimsonMods/actions/.github/workflows/mod-build.yml@master
    with:
      artifact-path: ./bin/Release/net6.0/VampireWebhook.dll
      project-name: VampireWebhook