name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: The tag to release.
        type: string

permissions:
  contents: write
  packages: write

jobs:
  release:
    uses: CrimsonMods/actions/.github/workflows/mod-release.yml@master
    with:
      release-tag: ${{ github.event_name == 'workflow_dispatch' && inputs.tag_name || github.ref_name }}
    secrets:
      thunderstore-key: ${{ secrets.THUNDERSTORE_KEY }}