name: Update Dependencies

on:
  schedule:
    - cron: '0 17 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: CrimsonMods/actions/.github/workflows/dependency-update.yml@master
    with:
      project-path: ./VampireWebhook.csproj
      target-branch: master